<?php /** @var \App\Model\User $user */

?>

<html>
    <head>

    </head>
    <body>
        
         <? if ($user): ?>
             <p> Вы вошли как <? echo $user->getName(); ?>
                 || <a href='/blog'> перейти в блог </a> ||
                 <? if ($user->isAdmin()): ?>
                     <a href="/admin">ADMIN</a> ||
                 <? endif;?>
                 <a href="/user/logout">Выйти</a> ||
             </p>
        <? endif; ?>
         <? if (!$user): ?>
             <p>
                 || <a href='/user/register'> Регистрация </a> || <a href="/user/login">Вход</a> ||
             </p>
         <? endif; ?>




    </body>
</html>

